image: ruby:2.3

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - gem install bundler
  - bundle install

rspec:
  script:
    - rails db:migrate RAILS_ENV=test
    - rspec

rubocop:
  script:
    - bundle exec rubocop -a
