Metrics/LineLength:
  Max: 140

Rails:
  Enabled: true

EndOfLine:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

AllCops:
  TargetRubyVersion: 2.3

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 18

Style/GuardClause:
  MinBodyLength: 5
