# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e653d01e50aa80551d57793f43958cebcf4280ab80671a7328149cc4a8305595f5eb626f3345c08ebc31edd1209730d1a20f580bb81488f253dd4c942545ad17

test:
  secret_key_base: e0aea41bf126c0bee572fa95a63b053c181d4db318618dd1ee3a9cb5bc705117151273fed8357184d7acce2fbcbdc5807d9f469e7b9d47e62098df1fe7066e92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
